name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: test
        run: |
          mkdir ooo
          echo "test pwd"
          pwd
          echo "test ls ~"
          ls ~
          docker ps -a
          echo "test docker ps -a"

      - name: Run a simple command
        run: |
          echo "Hello from my self-hosted runner!"
          uname -a
          pwd
